### ISSUE TITLE
PATH_EMPTY regex does not actually match empty path

### ISSUE THREAD

**Issue by milo-minderbinder** [python-hyper/rfc3986#88]
https://github.com/python-hyper/rfc3986/blob/164073434fe530e14ceca4ff6a0683e23e2fde48/src/rfc3986/abnf_regexp.py#L153

The `PATH_EMPTY` regex won't ever match anything when embedded within another regex, as it is in several places like here:
https://github.com/python-hyper/rfc3986/blob/164073434fe530e14ceca4ff6a0683e23e2fde48/src/rfc3986/abnf_regexp.py#L184-L190

This causes the `URIReference.is_absolute()` method to return an incorrect result for a URI with a scheme but no path. For example, `http:` (or even `http:?q=v`) is an absolute URI according to [section-4.3](https://datatracker.ietf.org/doc/html/rfc3986#section-4.3), but `URIReference.from_string('http:').is_absolute()` returns `False`.

There are likely other places where this causes intended matches to fail, but I have not tried to investigate further. It's a little odd looking, but a fix that would probably work is just to change the value of `PATH_EMPTY` to an empty string.

**Comment by handrews** [comment]
While `http` and `https` URIs [MUST have an authority component](https://www.rfc-editor.org/rfc/rfc9110#name-http-related-uri-schemes), the [`about` URI scheme](https://datatracker.ietf.org/doc/html/rfc6694#section-2.1) does not use an authority, allows an empty path, and allows a query string:

```ABNF
about-uri = "about:" about-token [ about-query ] [ about-fragment ]
     about-token = *pchar
     about-query = "?" query
     about-fragment = "#" fragment
     pchar     = <as specified in [RFC 3986, Appendix A](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A)>
     query     = <as specified in [RFC 3986, Appendix A](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A)>
     fragment  = <as specified in [RFC 3986, Appendix A](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A)>
```

So this bug can also be reproduced with a URI scheme that allows these forms, which I think would make these good cases to add to the test suite:

```Python
>>> rfc3986.__version__
'2.0.0'
>>> rfc3986.uri_reference('about:').is_absolute()
False
>>> rfc3986.uri_reference('about:?foo=bar').is_absolute()
False
```

**Comment by handrews** [comment]
Hmm... on further thought, an empty path is only allowed if an authority is present, and the authority cannot be empty (because the hostname cannot be empty):

```ABNF
      URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
```

`path-abempty` being on the line with `"//" authority` like that means that they go together, while the other lines below are alternatives to that whole first line.

So I now think this is not a bug, or if there is a bug the bug is that `about:` and `about:?foo=bar` should not parse.  The `about` URI scheme's syntax ABNF definitely allows for an empty `about-token` (which functions as the path), but I think RFC3986's disallowing of empty paths without an authority takes precedence.

I'll leave this for a project member to decide whether to close or not, but I'm going to close my PR for now.  It can be re-opened if needed, of course.

**Comment by handrews** [comment]
Oh wait there's also a `path-empty` that I forgot.  I've clearly been staring at ABNF for too long...

Re-opening my PR.
